server:
  port: 8090
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  application:
    name: springsecurityfirebaseauth
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beton_transport
    username: root
    password: my-secret-pw
  jpa:
    hibernate:
      ddl-auto: update


security:
  firebase-props:
    database-url: ${FIREBASE_DATABASE}
    enable-strict-server-session: false
    enable-check-session-revoked: false
    enable-logout-everywhere: false
    session-expiry-in-days: 5
  cookie-props:
    max-age-in-minutes: 7200
    http-only: true
    secure: true
    domain: ${DOMAIN}
    path: /
  allow-credentials: true
  allowed-origins:
    - https://${DOMAIN}
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Origin
    - Content-Type
    - Accept
    - Accept-Encoding
    - Accept-Language
    - Access-Control-Allow-Origin
    - Access-Control-Allow-Headers
    - Access-Control-Request-Method
    - X-Requested-With
    - X-Auth-Token
    - X-Xsrf-Token
    - Cache-Control
    - Id-Token
  allowed-public-apis:
    - /favicon.ico
    - /session/login
    - /public/**
    - /work-hours/**
    - /absent-days/**/**
    - /vacations/**
    - /settings/**
    - /work-hours-bank/**
    - /tours/**
    - /messenger/**
    - /ws/**
    - /test/**
    - /role/**
    - /users/**
    - /session/**
  valid-application-roles:
    - ROLE_SUPER
    - ROLE_ADMIN
    - ROLE_USER
    - ROLE_DRIVER
  super-admins: ${SUPER_ADMINS}
  test:
    login:
      enabled: ${TEST_LOGIN_ENABLED}
  exposed-headers:
    - X-Xsrf-Token